---
- name: Create Minecraft directory
  file:
    path: "{{ minecraft_server_directory }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: "0755"
  become: yes


- name: Download Minecraft Server JAR
  get_url:
    url: "{{ minecraft_server_jar_url }}"
    dest: "{{ minecraft_server_directory }}/{{ minecraft_server_jar }}"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_user }}"
    mode: '0755'
  become: yes
